// BlueprintGeneratedClass BP_AIFunctionLibrary.BP_AIFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UBP_AIFunctionLibrary_C : UBlueprintFunctionLibrary {

	void SeparateMontageAttackSectionsMap(struct TMap<struct FName, float> SectionsMap, struct UObject* __WorldContext, struct TMap<struct FName, float>& StationaryAttacks, struct TMap<struct FName, float>& RunningAttacks); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.SeparateMontageAttackSectionsMap // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1be0000
	void GetRandomActionMontageSection(struct TMap<struct FName, float> PossibleSections, struct UObject* __WorldContext, struct FName& OutSection); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetRandomActionMontageSection // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetNearestAlivePlayer(struct FVector Origin, float MaxDistance, struct UObject* __WorldContext, struct AIcarusPlayerCharacter*& Player); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetNearestAlivePlayer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetRandomAliveNearbyPlayer(struct FVector Origin, float NearbyDistance, struct UObject* __WorldContext, struct AIcarusPlayerCharacter*& Player); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetRandomAliveNearbyPlayer // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void MakeNPCAngry(struct AIcarusNPCGOAPCharacter* NPC, struct AActor* TargetActor, struct UObject* __WorldContext); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.MakeNPCAngry // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetNPCStatWithDefaultValue(struct AActor* SpawnableAI, struct FStatsEnum Stat, int32_t DefaultValue, struct UObject* __WorldContext, int32_t& Value); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetNPCStatWithDefaultValue // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure|Const) // @ game+0x1be0000
	void SetAllComponentsIgnoreCollision(struct AActor* ComponentActor, struct AActor* ActorToIgnore, bool ShouldIgnore, struct UObject* __WorldContext); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.SetAllComponentsIgnoreCollision // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	bool HasAIRetreated(struct UObject* Target, struct UObject* __WorldContext); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.HasAIRetreated // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1be0000
	void Create Knockback Damage Event(struct APawn* PawnDamageCauser, struct FVector DamageOrigin, float KnockbackForce, struct UObject* __WorldContext, struct TArray<struct AActor*>& AffectedTargets); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.Create Knockback Damage Event // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetClosestTargetableActor(struct AActor* SelfTargetable, enum class ERelationshipType RelationshipType, bool bUseMaxDistance, float MaxDistance, struct UObject* __WorldContext, struct AActor*& Actor); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetClosestTargetableActor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void SeparateMontageAttackSections(struct TArray<struct FName>& Sections, struct UObject* __WorldContext, struct TArray<struct FName>& StationaryAttacks, struct TArray<struct FName>& RunningAttacks); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.SeparateMontageAttackSections // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1be0000
	void GenerateLevelFromLocation(struct UObject* Context, struct FVector& Location, struct FRandomStream& Random Stream, struct UObject* __WorldContext, int32_t& Level); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GenerateLevelFromLocation // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GenerateLevel(struct FRandomStream& Random Stream, int32_t Min, int32_t Median, int32_t Max, struct UObject* __WorldContext, int32_t& Level); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GenerateLevel // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetZoneTextureSample(struct UObject* Context, struct FVector& Location, struct UObject* __WorldContext, struct FAISpawnZonesRowHandle& Zone); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetZoneTextureSample // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void IsTargetable(struct AActor* Actor, struct UObject* __WorldContext, bool& IsTargetable); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.IsTargetable // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1be0000
	void CanTargetActorBeAttacked(struct AActor* TargetActor, struct AActor* Attacker, struct UObject* __WorldContext, bool& CanAttack); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.CanTargetActorBeAttacked // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetProspectSpawnConfig(struct UObject* __WorldContext, struct FAISpawnConfigData& SpawnConfig, bool& Success); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetProspectSpawnConfig // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void GetBlockingDurableActor(struct AActor* InFrontOf, float ForwardTraceDistance, struct UObject* __WorldContext, struct AActor*& BlockingActor); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.GetBlockingDurableActor // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
	void UpdateLastHostileStimuliLocation(struct AAIController* Controller, struct AActor* TargetActor, struct FVector OptionalOverrideLocation, float OnlyIfCloserThanExisting, struct UObject* __WorldContext); // Function BP_AIFunctionLibrary.BP_AIFunctionLibrary_C.UpdateLastHostileStimuliLocation // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1be0000
};

